title: "Datu Adiatma"
title_separator: "-"
logo: "/assets/images/Signature_Thick.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Yoseph Datu Adiatma personal / profesional website.
  I am a geologist with expertise in isotope geochemistry
  sedimentology, and stratigraphy.
twitter_username: mas_datu
github_username: datuadiatma
minimal_mistakes_skin: contrast
search: true

# Enable copy code
enable_copy_code_button: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-LN6BF0WPLF"
    anonymize_ip         : # true, false (default)

comments:
  provider: "disqus"
  disqus:
    shortname: "adtma"


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Datu Adiatma"
  avatar : "/assets/images/ProfPic_2025.jpg"
  bio    : "Geologist<br>Postdoc at FSU<br>EOAS"
  links:
    - label: "Contact"
      icon: "fa-solid fa-envelope"
      url: "https://www.adtma.pw/contact"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.adtma.pw"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/datuadiatma"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=9mauI8YAAAAJ&hl=en"
    - label: "Bluesky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/datu.bsky.social"
    - label: "Strava"
      icon: "fab fa-fw fa-strava"
      url: "https://www.strava.com/athletes/24362823"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/datuadiatma"
    - label: "Threads"
      icon: "fa-brands fa-threads"
      url: "https://www.threads.net/@datuadiatma"


footer:
  links:
    - label: "Contact"
      icon: "fa-solid fa-envelope"
      url: "https://www.adtma.pw/contact"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=9mauI8YAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/datuadiatma"
    - label: "Bluesky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/datu.bsky.social"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
      teaser: /assets/images/teaser_1.png
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
      share: false
      related: false
  # _news
  - scope:
      path: ""
      type: news
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true


category_archive:
  type: liquid
  path: /categories/
  
tag_archive:
  type: liquid
  path: /tags/

collections:
  news:
    output: true
    permalink: /:collection/:path/
